// Auto-generated by update-sketches.js – DO NOT EDIT
window.SKETCH_LIST = [
  "1.The Number Line.js",
  "2.Interaction Line.js",
  "3.Make your own shape.js",
  "4.Challendge.js",
  "5.Negative.js",
  "6.Zoom.js",
  "7.decimal.js",
  "8.Absolute Value.js",
  "9.Distance Between.js",
  "10.Distance Between Calculation.js",
  "11.Coordinate.js",
  "12.Coordinate Practice.js",
  "13.3D Coordinate.js",
  "14.3D Coordinate free movement.js",
  "15.Angle.js",
  "16.Angle Complimentary and Supplementary .js",
  "17.Angle of Polygons.js"
];
